routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('hola',function(){
    return "hola  mundo";
});
Route::get('/', function () {
    return view('auth.login');
});

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');;
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('widgets', function () {
        return view('layouts.widgets');
    });
    Route::get('layout', function () {
        return view('layouts.layout');
    });
    Route::get('metrics', function () {
        return view('layouts.metrics');
    });
    
    Route::resource('products','ProductController'); 
    Route::resource('users','UsersController');
    Route::resource('users.post','PostController');
    
//----------- reset password -----
    

    
    // cre q es get showLinkRequestForm
    // Route::get('reset_password','Auth\AccountsController@reset_password');
    // Route::get('reset_password','Auth\AccountsController@forgot_password');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Users.php
<?php
  
namespace App;
  
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Traits\UpdateGenericClass;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Notifications\ResetPassword;
   
class Users extends Model
{
    use Notifiable;

    //
    use UpdateGenericClass;

    protected $table='users';

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }
    // relacion de 1-M
    public function post(){
        return $this->hasMany(Post::class, 'user_creator_id', 'id');
    }
    // relacion de N-M
    public function comments(){
        return $this->belongsToMany('\App\Comment','comment','id', 'user_id')->withTimestamps(); 
    }


    public function getNameAttribute($value)
    {
        return $this->attributes['name']=strtoupper($value);
    }
    public function getLastnameAttribute($value)
    {
        return strtoupper($value);
    }
    public function getUserroleAttribute($value)
    {
        return ucfirst($value);
    }
    

    //---------------SCOPES------------------//

    public function scopeFindId($query,$id){
        return $query->where('id','=',$id);

    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;


use App\Users;
use App\Helper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    
    public function index()
    {
        $users=Users::get();
        return view('users.index',compact('users'));
    }

    public function create()
    {

        return view('users.create');
        
    }

    public function store(Request $request)
    {

        $datosUser=request()->except('_token');
        
        if($request->hasFile('photo')){
        
            $datosUser['photo']=Helper::add_img($request);
            
        }
        Users::insert($datosUser);

        return redirect('users')->with('Success','Product created successfully.');
        
    }


    public function show(Users $user)
    {
            
            return view('users.show',compact('user'));
    }
    
    public function edit($id)
    {
        
        $user=Users::findOrFail($id);   
        return view('users.edit', compact('user'));

    }

    public function update(Request $request, $id)
    {
        //
        $datosUser=request()->except(['_token', '_method']);

        if($request->hasFile('photo')){

            $user= Users::findOrFail($id);

            Storage::delete('public/.$user->photo');

            $datosUser['photo']=$request->file('photo')->store('uploads','public');
        }
        // where('id','=',$id)->update($datosUser); va despues de users::
        Users::where('id','=',$id)->update($datosUser);
        return redirect('users')->with('Mensaje','user successfully modified');
    }

    public function destroy($id)
    {
        
        $user= Users::find($id);
            //dd($user);
                if(Storage::delete('public/.$user->photo')){
                    
                };
                $user->delete();
            return redirect('users');
    }
    

}

resources/views/Users/create.blade.php
@extends('layouts.principal')
@section('content')

<form class="form-horizontal" action="{{ url('users')}}" method="post" enctype="multipart/form-data">
{{ csrf_field() }}

@include('users.partials.form',['Modo'=>'crear'])
</form> 
@include('layouts.scripts')
@stop

resources/views/Users/edit.blade.php
@extends('layouts.principal')
@section('content')
<form action="{{ url('/users/'.$user->id) }}" method="post" class="form-horizontal" enctype="multipart/form-data"> 
{{ csrf_field() }}
{{ method_field('PATCH') }}

@include('users.partials.form',['Modo'=>'editar'])
</form>

@stop

resources/views/Users/index.blade.php
@extends('layouts.principal')
@section('content')

@if(Session::has('Mensaje')){{
    Session::get('Mensaje')
}}
@endif
<div class="row wrapper border-bottom white-bg">
    <div class="col-lg-12">
        <h2>Users</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('layout') }}">Home</a>
            </li>
            <li class="active">
                <strong>Users</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper wrapper-contentt">
    <div class="row">
        <div class="class="col-lg-12>
            <div class="ibox-content">
                <a href="{{ url('/users/create') }}" class="btn btn-primary m-b">Add Users</a>
            
                <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-example" >
                    <thead class="thead-light">
                        <tr>
                            <th>ID</th>
                            <th>Photo</th>
                            <th>Name</th>
                            <th>Lastname</th>
                            <th>Email</th>
                            <th>User Role</th>
                            <th width="200px">Acctions</th>
                        </tr>
                    </thead>

                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{$loop->iteration}}</td>
                            <td>
                            <img src="{{ asset('storage').'/'.$user->photo }}" class="img-circle" alt="" width="50">
                            </td>
                            <td>{{ $user->name}}</td>
                            <td>{{ $user->lastname}}</td>
                            <td>{{ $user->email}}</td>
                            <td>{{ $user->userrole}}</td>
                            <td>                           
                               <a class="btn btn-primary btn-xs" href="{{ route('users.show',$user->id) }}">Show</a> /

                                <a class="btn btn-success  btn-xs" href="{{ route('users.post.index',$user->id) }}">View Post</a> /

                                <a class="btn btn-warning btn-xs" href="{{ url('/users'.$user->id.'/edit') }}" enctype="multipart/form-data">Edit</a> /

                                <form method="post" action="{{ url('users/'.$user->id) }}">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="btn btn-danger btn-xs" onclick="return confirm('¿Delete?');">Delete</button> 
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/Users/show.blade.php
@extends('layouts.principal')
@section('content')
    
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Users</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $user->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Last Name:</strong>
                {{ $user->lastname}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $user->email}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Photo:</strong>
                {{ $user->photo }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>About me:</strong>
                {{ $user->aboutme }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>License Number:</strong>
                {{ $user->licensenumber}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Zip Code:</strong>
                {{ $user->zipcode}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>User Role:</strong>
                {{ $user->userrole}}
            </div>
        </div>
</div>

@stop