routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('hola',function(){
    return "hola  mundo";
});
Route::get('/', function () {
    return view('auth.login');
});

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');;
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('widgets', function () {
        return view('layouts.widgets');
    });
    Route::get('layout', function () {
        return view('layouts.layout');
    });
    Route::get('metrics', function () {
        return view('layouts.metrics');
    });
    
    Route::resource('products','ProductController'); 
    Route::resource('users','UsersController');
    Route::resource('users.post','PostController');
    
//----------- reset password -----
    

    
    // cre q es get showLinkRequestForm
    // Route::get('reset_password','Auth\AccountsController@reset_password');
    // Route::get('reset_password','Auth\AccountsController@forgot_password');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\UpdateGenericClass;


class Post extends Model
{
    
    use UpdateGenericClass;

    protected $table='post';

    protected $fillable = [
        'case', 'description','user_creator_id',
    ];
    

    public function user(){
        return $this->belongsTo('App\Users', 'user_creator_id', 'id');
    }
    public function comment(){
        return $this->belongsToMany(Comment::class ,'comment','id', 'post_id')->withTimestamps();
    }

    public function getCaseAttribute($value)
    {
        return strtoupper($value);
    }




    //--------------SCOPES---------------//

    public function scopeByUser($query,$id){
        return $query->where('user_creator_id','=',$id);
    }
    public function scopeFindIqualId($query,$id){
        return $query->where('user_creator_id',$id);
    }


    
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Users;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{

    public function index($id){

        $user = Users::find($id);

        $posts=Post::findIqualId($id)->get();
        return view('posts.index',compact('user'),compact('posts'));
         
    }

    public function create($id){
        $user = Users::find($id);
        return view('posts.create', compact('user'));
        
    }


    public function store(Request $request, $id){
        $datosUser=request()->except('_token');
        $datosUser['user_creator_id']=$id;
        Post::insert($datosUser);

        return redirect('users/'.$id.'/post');
    }

    
    public function edit(Request $request){

        $post=Post::find($request->post);
        $user=$request->user;
       
        return view('posts.edit', compact('post','user'));

    }

    
    
    public function update(Request $request , $id){

        $datosUser=request()->except(['_token', '_method']);
        ///$datosUser['user_creator_id']=$request->user;
        $post=Post::where('id','=',$request->post)->update($datosUser);
        return redirect('users/'.$request->user.'/post');

    }

    public function destroy(Users $user , Post  $post){
        
        $post->delete();
        return redirect('users/'.$user->id.'/post');

    }

    public function listaPost($id){
        $posts=Post::byUser($id)->get();
        $users=Users::paginate(5);

        return view('posts.index',compact('users','posts'));       
    }

}

resources/views/posts/create.blade.php
@extends('layouts.principal')
@section('content')
@include('layouts.head')
<form class="form-horizontal" action="{{ url('/users/'.$user->id.'/post')}}" method="post" enctype="multipart/form-data">
 
@csrf
@include('posts.partials.form',['Modo'=>'crear'])
</form> 
@include('layouts.scripts')
@stop

resources/views/posts/edit.blade.php
@extends('layouts.principal')
@section('content')

<form action="{{ url('users/'.$user.'/post/'.$post->id) }}" method="post" class="form-horizontal" enctype="multipart/form-data"> 
{{ csrf_field() }}
{{ method_field('PATCH') }}

@include('posts.partials.form',['Modo'=>'editar'])
</form>

@stop

resources/views/posts/index.blade.php
@extends('layouts.principal')
@section('content')

@if(Session::has('Mensaje')){{
    Session::get('Mensaje')
}}
@endif
<div class="row wrapper border-bottom white-bg">
    <div class="col-lg-12">
        <h2>Posts</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('layout') }}">Home</a>
            </li>
            <li class="active">
                <strong>Posts</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper wrapper-contentt">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-content">
            
            
            <a href="{{ route('users.post.create',$user->id) }}" class="btn btn-primary m-b">New Post</a>

                <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-example" >
                    <thead class="thead-light">
                        <tr>
                            <th>ID</th>
                            <th>Tittle</th>
                            <th>Description</th>
                            <th width="200px">Acctions</th>
                        </tr>
                    </thead>

                    <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td>{{$loop->iteration}}</td>
                            
                            <td>{{ $post->case}}</td>
                            <td>{{ $post->description}}</td>
                            <td>                           
                            <!--<a class="btn btn-info" href="{{ url('/users/'.@$user->id.'/post/',$post->id) }}">Show</a>-->

                                <a class="btn btn-primary" href="{{ url('/users/'.@$user->id.'/post/'.$post->id.'/edit') }}" enctype="multipart/form-data">Edit</a>

                                <form method="post" action="{{ url('/users/'.@$user->id.'/post/'.$post->id) }}">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('¿Delete?');">Delete</button> 
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.principal')
@section('content')
    
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('post.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tittle:</strong>
                {{ $post->case }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $post->description}}
            </div>
        </div>
</div>

@stop